### PR TITLE
Allow band specification for download/export

### PR DESCRIPTION
**Pull request by dugalh**
- Add *bands* parameter to download and export API and CLI.

### CODE REVIEW

**Comment by brownag** [comment]
Hey @dugalh this was a wonderful addition. I have been installing the development version to make use of it. 

Do you have plans to bump the version available from PyPI in near future? Thanks for all your work

**Comment by dugalh** [comment]
Hi @brownag.  OK, great - I'm happy it is being used.  I should get another release out in a week or two.  There are a couple of other things I want to include if possible.

**Comment by dugalh** [comment]
Hi @brownag.  I have published [v1.7.1](https://github.com/leftfield-geospatial/geedim/releases/tag/v1.7.1) with the bands update to PyPI.  I haven't had a chance to look at the other features yet...

**Comment by brownag** [comment]
That's great, thanks @dugalh!

**Pull request merged**
